#  SpinEverydayBot
#  Copyright © 2016-2021 Evgeniy Filimonov <evgfilim1@yandex.ru>
#
#  This program is free software: you can redistribute it and/or modify it under the terms of the
#  GNU Affero General Public License as published by the Free Software Foundation, either version 3
#  of the License, or (at your option) any later version.
#  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
#  even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Affero General Public License for more details.
#  You should have received a copy of the GNU Affero General Public License along with this program.
#  If not, see <http://www.gnu.org/licenses/>.

"""
Init.

Revision ID: 67f1cdf26b82
Revises:
Create Date: 2021-07-19 05:42:56.116217+00:00

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "67f1cdf26b82"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("wotd_registered", sa.Boolean(), nullable=False),
        sa.Column("wotd", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chats",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("raffle_name", sa.String(), nullable=True),
        sa.Column("winner_id", sa.BigInteger(), nullable=True),
        sa.Column("language", sa.String(), nullable=True),
        sa.Column("timezone_offset_min", sa.SmallInteger(), nullable=False),
        sa.Column("auto_at", sa.Time(), nullable=True),
        sa.Column("fast", sa.Boolean(), nullable=True),
        sa.Column("admin_only", sa.Boolean(), nullable=True),
        sa.Column("opt_in", sa.Boolean(), nullable=True),
        sa.Column("show_user_list", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["winner_id"], ["users.id"], onupdate="cascade", ondelete="set null"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_texts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("group", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group", "order"),
    )
    op.create_table(
        "chat_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["chat_id"], ["chats.id"], onupdate="cascade", ondelete="cascade"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], onupdate="cascade", ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "chat_id"),
    )
    op.create_table(
        "win_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_user_id", sa.Integer(), nullable=False),
        sa.Column("won_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["chat_user_id"], ["chat_users.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("win_history")
    op.drop_table("chat_users")
    op.drop_table("chat_texts")
    op.drop_table("chats")
    op.drop_table("users")
    # ### end Alembic commands ###
